version: '3'
services:
  meshforms:
    healthcheck:
      test: curl --fail http://127.0.0.1:80/join || exit 1
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
    networks:
      - ui
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
        # .nycmesh.net URL (with HTTPS)
      - "traefik.http.routers.meshforms.rule=Host(`forms.grandsvc.mesh.nycmesh.net`)"
      - "traefik.http.routers.meshforms.entrypoints=websecure"
      - "traefik.http.routers.meshforms.tls=true"
      - "traefik.http.routers.meshforms.tls.certresolver=grandsvcresolver"
        # .nycmesh.net Redirect insecure traffic
      - "traefik.http.routers.meshforms-insecure.rule=Host(`forms.grandsvc.mesh.nycmesh.net`)"
      - "traefik.http.routers.meshforms-insecure.entrypoints=web"
      - "traefik.http.middlewares.meshforms-https.redirectscheme.scheme=https"
      - "traefik.http.routers.meshforms-insecure.middlewares=meshforms-https@docker"
        # .mesh URL
      - "traefik.http.routers.meshforms-mesh.rule=Host(`forms.grandsvc.mesh`)"
      - "traefik.http.routers.meshforms-mesh.entrypoints=web"

    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

networks:
  ui:
    external: $COMPOSE_EXTERNAL_NETWORK
    name: $COMPOSE_NETWORK_NAME
