version: '3'
services:
  meshforms:
    healthcheck:
      test: curl --fail http://127.0.0.1:80/join || exit 1
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
    networks:
      - ui
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.meshforms.entrypoints=web,websecure"
      - "traefik.http.routers.meshforms.rule=Host(`forms.grandsvc.mesh.nycmesh.net`)"
      - "traefik.http.routers.meshforms.tls.certresolver=grandsvcresolver"
      - "traefik.http.routers.meshforms-mesh.rule=Host(`forms.grandsvc.mesh`)"
      - "traefik.http.routers.meshforms-mesh.entrypoints=web"

    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile

networks:
  ui:
    external: true
    name: traefik-net
